num=[1 -2 0.8];
den=[1 2 2 1];
subplot(231);
pzmap(num,den);
t=0:0.01:15;
subplot(232);
impulse(num,den,t);
grid on;
subplot(233);
step(num,den,t);
grid on;
omega=0:0.01:2*pi;
H=freqs(num,den,omega);
subplot(234);
plot(omega,abs(H));
title('·ùÆµÏìÓ¦');
grid on;
subplot(235);
plot(omega,angle(H));
grid on;
title('ÏàÆµÏìÓ¦');