a=[1,-1.5,0.5];
b=[1];
[h,n]=impz(b,a);
subplot(321);
stem(n,h);
title('冲激响应');
[s,n]=stepz(b,a);
subplot(322);
stem(n,s);
title('阶跃响应');

N=20;
n=0:N-1;
x0=zeros(1,N);
y0=[4 10];
x=0.25.^n;
zi=filtic(b,a,y0);
yzi=filter(b,a,x0,zi);
zi1=filtic(b,a,0);
yzs=filter(b,a,x,zi);
y=filter(b,a,x,zi);
yy=1.*(1/2).^n+1/3.*(1/4).^n+2/3.;
subplot(323);
stem(n,yzi);
title('系统的零输入响应');
subplot(324);
stem(n,yzs);
title('系统的零状态响应');
subplot(325);
stem(n,y,'fill','r');
hold on;
stem(n,yy,'b');
title('系统的全响应与理论计算的结果比较');
